---
title: "4th corner analyses for neophytes from the Calilegua National Park, Argentina"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("r-code/00_functions.R")
load("data/workingdata.RData")
using("ggplot2","tidyverse","knitr","mvabund","ade4")
```



https://rpubs.com/dwarton/68823
https://heather-grab.github.io/Entom-4940/rql.html
http://www.esapubs.org/archive/ecol/E095/002/suppl-1.pdf

```{r}
speEnvTraits = list()

spe4c = neophytesPlotPercent %>% dplyr::select(-Aru.don,-Leo.jap,-Leu.leu,-Psi.gua) # remove singletons
env4c = preds %>% dplyr::select(site_id,plot_id,ring1,slope,herbAbund.4,humus.0)
#env4c$ring1 = as.numeric(as.character(env4c$ring1))
#env4c$herbAbund.4 = as.numeric(as.character(env4c$herbAbund.4))
#env4c$humus.0 = as.numeric(as.character(env4c$humus.0))



speEnv4c = data.frame(dplyr::left_join(spe4c,env4c,by=c("site_id","plot_id")))
rownames(speEnv4c) = speEnv4c$plot_id
# speEnvTraits[[1]] = speEnv4c  %>% dplyr::select(Cyn.dac,Cyp.iri,Ele.ind,Eup.hir,Meg.max,Mel.alb,Ric.com,Son.asp,Sor.hal)

speEnvTraits[[1]] = speEnv4c  %>% dplyr::select(Cyn.dac,Meg.max,Ric.com)


speEnvTraits[[2]] = speEnv4c  %>% dplyr::select(ring1,slope,herbAbund.4,humus.0)


# Traits
Traits4c = plantTraits[which(plantTraits$plant_id %in% colnames(spe4c)),] # select neophytes
selectedTraits = c("dispersal_distance","height_m_max","growth_form","lifespan","growth_form","growth_rate")
Traits4c = Traits4c[which(Traits4c$TraitName %in%  selectedTraits),]
Traits4c %<>% dplyr::select(plant_id,TraitName,Trait_id)
Traits4c =  data.frame(tidyr::spread(Traits4c,key=TraitName,value=Trait_id))
rownames(Traits4c) = Traits4c$plant_id
Traits4c = Traits4c[,-1]

# Traits4c$dispersal_distance[which(Traits4c$dispersal_distance=="DispS")]=1
# Traits4c$dispersal_distance[which(Traits4c$dispersal_distance=="DispM")]=2
# Traits4c$dispersal_distance[which(Traits4c$dispersal_distance=="DispL")]=3
# Traits4c$dispersal_distance = as.numeric(as.character(Traits4c$dispersal_distance))
# 
# Traits4c$height_m_max[which(Traits4c$height_m_max=="HeightMaxL")]=1
# Traits4c$height_m_max[which(Traits4c$height_m_max=="HeightMaxM")]=2
# Traits4c$height_m_max[which(Traits4c$height_m_max=="HeightMaxH")]=3
# Traits4c$height_m_max = as.numeric(as.character(Traits4c$height_m_max))
# 
# Traits4c$tolerance_fire[which(Traits4c$tolerance_fire=="TolFireL")]=1
# Traits4c$tolerance_fire[which(Traits4c$tolerance_fire=="TolFireH")]=2
# Traits4c$tolerance_fire = as.numeric(as.character(Traits4c$tolerance_fire))
# 
# Traits4c$growth_form[which(Traits4c$growth_form=="Grass")]=1
# Traits4c$growth_form[which(Traits4c$growth_form=="Herb")] =2
# Traits4c$growth_form[which(Traits4c$growth_form=="Tree")] =3
# Traits4c$growth_form = as.numeric(as.character(Traits4c$growth_form))
# 
# Traits4c$growth_rate[which(Traits4c$growth_rate=="GrowthM")]=1
# Traits4c$growth_rate[which(Traits4c$growth_rate=="GrowthR")]=2
# Traits4c$growth_rate = as.numeric(as.character(Traits4c$growth_rate))
# 
# Traits4c$lifespan[which(Traits4c$lifespan=="An")]=1
# Traits4c$lifespan[which(Traits4c$lifespan=="Bi")] =2
# Traits4c$lifespan[which(Traits4c$lifespan=="Pe")] =3
# Traits4c$lifespan = as.numeric(as.character(Traits4c$lifespan))

speEnvTraits[[3]] = Traits4c

names(speEnvTraits) = c("spe","env","traits")
```



```{r}
afcL.speEnvTraits <- dudi.coa(speEnvTraits$spe, scannf = FALSE)
acpR.speEnvTraits <- dudi.hillsmith(speEnvTraits$env, row.w = afcL.speEnvTraits$lw,scannf = FALSE)
acpQ.speEnvTraits <- dudi.pca(speEnvTraits$traits, row.w = afcL.speEnvTraits$cw,scannf = FALSE)
rlq.speEnvTraits <- rlq(acpR.speEnvTraits, afcL.speEnvTraits, acpQ.speEnvTraits,scannf = FALSE)

plot(rlq.speEnvTraits)
summary(rlq.speEnvTraits)
```


```{r}
nrepet <- 49999
four.comb.speEnvTraits <- fourthcorner(speEnvTraits$env, speEnvTraits$spe,
speEnvTraits$traits, modeltype = 6, p.adjust.method.G = "none",
p.adjust.method.D = "none", nrepet = nrepet)

plot(four.comb.speEnvTraits, alpha = 0.05, stat = "D2")
```



```{r}
fit=mvabund::traitglm(speEnvTraits$spe,speEnvTraits$env,speEnvTraits$traits)
summary(fit, nBoot=10)
```

