---
title: "Hierarchical trait trees"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
This document creates hierarchical trees of neophytes collected in the Calilegua National Park, Argentina.

# Load data & functions
```{r}
source("r-code/00_functions.R")
load("data/workingdata.RData")
using("tidyr","dplyr","tibble","taxa","metacoder","ggplot2","magrittr")
```



```{r}
# veg_data=data.frame(t(veg[,-c(1:3)]))
# colnames(veg_data)=veg$plot_id
# veg_data$species = rownames(veg_data)

veg_data = neophytes
veg_data = dplyr::left_join(veg_data,taxonomy,by=c("plant_id"="plant_id"))

```




# Heattrees

## Heat tree using plant taxonomy
```{r}
NeophytesTaxmap_Cover =parse_tax_data(veg_data,
               class_cols = "taxonomy",
               class_sep=";",
               class_regex = "^([a-z]{0,1})_{0,2}(.*)$",
               class_key = c("tax_rank" = "taxon_rank", "name" = "taxon_name"))
print(NeophytesTaxmap_Cover)
```

```{r}
set.seed(2020) 
NeophytesTaxmap_Cover %>%
heat_tree(node_label = taxon_names,
          node_color = n_obs,
          node_size = n_obs,
          layout = "da",
          initial_layout = "re")
```



## Traits
```{r}
Traits = dplyr::inner_join(plantTraits,plantTraitsHierarchy,by=c("TraitName"="TraitName","Trait"="Trait","Trait_id"="Trait_id"))
Traits %<>% select (plant_id,hierarchy)
veg_data = neophytes
veg_trait_data = dplyr::inner_join(veg_data,Traits,by=c("plant_id"="plant_id"))
```

```{r}
NeophytesTraitsTaxmap = NULL
NeophytesTraitsTaxmap = parse_tax_data(veg_trait_data,
               class_cols = "hierarchy",
               class_sep=";",
               class_regex = "^([a-z]{0,1})_{0,2}(.*)$",
               class_key = c("tax_rank" = "taxon_rank", "name" = "taxon_name"))
print(NeophytesTraitsTaxmap)

set.seed(2020) 
NeophytesTraitsTaxmap %>%
heat_tree(node_label = taxon_names,
          node_color = n_obs,
          node_size = n_obs,
          layout = "da",
          initial_layout = "re")
```



## active vs. inactive
```{r}
Traits = dplyr::inner_join(plantTraits,plantTraitsHierarchy,by=c("TraitName"="TraitName","Trait"="Trait","Trait_id"="Trait_id"))
Traits %<>% select (plant_id,Trait_id,hierarchy)


# reshape dataset
## trait_id/sites 1 2
## trait1
## trait2

veg_data = data.frame(neophytesPlotPercent)
rownames(veg_data) = paste("plot_",veg_data$plot_id,sep="")
veg_data = veg_data %>% dplyr::select(-site_id,-ring,-plot_id)
veg_dataT = transpose_df(veg_data)
colnames(veg_dataT)[1] = "plant_id"

# combine veg and trait datasets
veg_trait_data = dplyr::inner_join(Traits,veg_dataT,by=c("plant_id"="plant_id"))
```

```{r}
NeophytesTraitsTaxmap = NULL
NeophytesTraitsTaxmap = parse_tax_data(veg_trait_data,
               class_cols = "hierarchy",
               class_sep=";",
               class_regex = "^([a-z]{0,1})_{0,2}(.*)$",
               class_key = c("tax_rank" = "taxon_rank", "name" = "taxon_name"))
print(NeophytesTraitsTaxmap)

set.seed(2020) 
NeophytesTraitsTaxmap %>%
heat_tree(node_label = taxon_names,
          node_color = n_obs,
          node_size = n_obs,
          layout = "da",
          initial_layout = "re")
```

# inactive vs active
```{r}
sites$plot = paste("plot_",sites$plot_id,sep="")
NeophyteSites = sites[-which(!sites$plot_id %in% neophytesPlotPercent$plot_id),]


# dat = NeophytesTraitsTaxmap$data$tax_data[,-c(1:4)]
# dat[dat>0]=1
# NeophytesTraitsTaxmap$data$tax_data[,-c(1:4)] = dat
# NeophytesTraitsTaxmap$data$tax_abd=calc_taxon_abund(NeophytesTraitsTaxmap,"tax_data")
# NeophytesTraitsTaxmap$data$diff_table <- compare_groups(NeophytesTraitsTaxmap,data="tax_abd", cols=NeophyteSites$plot,groups=NeophyteSites$activity)


NeophytesTraitsTaxmap$data$rel_abd=calc_obs_props(NeophytesTraitsTaxmap,"tax_data")
NeophytesTraitsTaxmap$data$tax_rel_abd=calc_taxon_abund(NeophytesTraitsTaxmap,"rel_abd")



NeophytesTraitsTaxmap$data$diff_table <- compare_groups(NeophytesTraitsTaxmap,data="tax_rel_abd", cols=NeophyteSites$plot,groups=NeophyteSites$ring)
#View(NeophytesTraitsTaxmap$data$diff_table)


dat=NeophytesTraitsTaxmap$data$diff_table
NeophytesTraitsTaxmap$data$diff_table=dat[which(dat$treatment_2!="ref"),]

set.seed(1)
NeophytesTraitsTaxmap %>%
  heat_tree_matrix(data = "diff_table",
                   node_size=n_obs,
                   node_label = taxon_names,
                   node_color = log2_median_ratio,
                   #node_color = log2_median_ratio,
                   node_color_range = diverging_palette(),
                   node_color_axis_label="Mean difference",
                   node_color_interval = c(-1,6),
                   layout="davidson-harel", initial_layout="reingold-tilford")
```

